import MainLayout, { Providers } from '@/shared/ui/layouts/main-layout';
import './globals.css';
// import { Inter } from 'next/font/google';
import 'antd/dist/reset.css';

// const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ru'>
      {/* <body className={inter.className}> */}
      <body>
        <Providers>
          <MainLayout>{children}</MainLayout>
        </Providers>
      </body>
    </html>
  );
}
